name: Rakit APK Kios

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode
        uses: actions/checkout@v4

      - name: Siapkan Sistem Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Gunakan Mesin Gradle Lawas
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '7.4.2'

      - name: Buat Surat Izin Palsu (Bypass Firebase)
        run: |
          echo '{ "project_info": { "project_number": "123", "project_id": "dummy" }, "client": [ { "client_info": { "mobilesdk_app_id": "1:123:android:abc", "android_client_info": { "package_name": "mgks.os.webview" } }, "api_key": [ { "current_key": "dummy" } ] } ], "configuration_version": "1" }' > app/google-services.json

      - name: Proses Membangun APK
        run: gradle assembleDebug

      - name: Simpan dan Siapkan Unduhan
        uses: actions/upload-artifact@v4
        with:
          name: APK-Kios-SPMB-2026
          path: app/build/outputs/apk/debug/*.apk
